# Generated by Django 5.2.5 on 2025-08-13 15:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=2000)),
                ('data_nascimento', models.DateField()),
                ('serie', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('imagem', models.CharField(blank=True, max_length=1000, null=True)),
                ('sinopse', models.CharField(blank=True, max_length=2000, null=True)),
                ('ano_lancamento', models.IntegerField(blank=True, null=True)),
                ('generos', models.CharField(blank=True, max_length=100, null=True)),
                ('autor', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=1000)),
                ('anexo', models.CharField(blank=True, max_length=2000, null=True)),
                ('data_de_criacao', models.DateField(default=datetime.date.today)),
                ('data_de_entrega', models.DateField(blank=True, null=True)),
                ('links', models.CharField(blank=True, max_length=2000, null=True)),
                ('nota', models.FloatField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saberacao.aluno')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saberacao.livro')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
    ]
