# Generated by Django 5.2.5 on 2025-08-13 16:17

import saberacao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saberacao', '0003_remove_aluno_email_remove_aluno_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='atividades/anexos/', validators=[saberacao.models.validate_file_extension]),
        ),
    ]
