# Generated by Django 5.2.5 on 2025-08-18 11:52

import saberacao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saberacao', '0004_alter_atividade_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='matricula',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='aluno',
            name='primeiro_nome',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='aluno',
            name='sobrenome',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='atividades', validators=[saberacao.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='livros/'),
        ),
    ]
