# Generated by Django 5.2.5 on 2025-08-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saberacao', '0005_aluno_matricula_aluno_primeiro_nome_aluno_sobrenome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.TextField(max_length=150, unique=True),
        ),
    ]
